version: "3"
services:
  web:
    image: carlosgg0/practica2:parte1
    ports:
      - "8080:80" 
    environment:
      - REDIS_HOST=redis
    networks:
      - webnet


  redis:
    image: redis
    ports:
      - "6379:6379"   
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet


  zookeeper:
    image: zookeeper:3.8.0 # Especificar una versión para reproducibilidad
    hostname: zookeeper
    ports:
      - "2181:2181" # Zookeeper 
    environment: 
      ZOO_STANDALONE_ENABLED: "true"
    networks:
      - webnet
      
networks:
  webnet:
